using Dman.LSystem.SystemRuntime.NativeCollections;
using Dman.Utilities.Math;
using Unity.Mathematics;
using UnityEngine;

namespace Dman.LSystem.SystemRuntime.Turtle
{
    /// <summary>
    /// data generated by the pre-process of stem instances. for example, the depth is generated by 
    ///     summing the depth up in a single thread up the tree
    /// This should be the minimal amount of data which benefits from single-threaded computation
    ///     and can't be worked out in parallel
    /// </summary>
    public struct TurtleStemGenerationData
    {
        public float uvDepth;
        public float normalizedVertexAngleOffset;
        public bool uvPositiveRun;
    }

    public struct TurtleStemPreprocessParallelData
    {
        public float uvLength;
        public float normalizedTriangleIndexOffset;
    }
}
