[package]
name = "system_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "system_runtime_rustlib" # the name of the library that will be generated
crate-type = ["rlib", "dylib"]

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "diffusion_benchmark"
harness = false
[[bench]]
name = "my_benchmark"
harness = false

[dependencies]
