[package]
name = "system_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "system_runtime_rustlib" # the name of the library that will be generated
crate-type = ["dylib"]

[build-dependencies]
csbindgen = {path = "C:/source/rust/csbindgen/csbindgen"}


[dependencies]
