on: [pull_request]
name: benchmark pull requests
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy cargo ci toml over ci toml
        run: cp Extern/Rust/system_runtime/Cargo.ci.toml Extern/Rust/system_runtime/Cargo.toml
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "Extern/Rust/system_runtime"
          # Needed. The name of the branch to compare with. This default uses the branch which is being pulled against
          branchName: ${{ github.base_ref }}